const $=id=>document.getElementById(id);let lastResult=null,offset=0;
async function api(path,options){const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.message||data.error?.message||data.error||'请求失败');return data;}
function text(tag,value,cls){const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==button.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));if(button.dataset.tab==='resources')loadRecords();if(button.dataset.tab==='governance')loadStatus();});
$('preview').onclick=()=>{$('molecule').src='/api/molecule?smiles='+encodeURIComponent($('smiles').value);};
$('preset').onchange=()=>{if($('preset').value){$('smiles').value=$('preset').value;$('preview').click();}};
function treeView(node){const el=document.createElement('div');el.className=node.type==='reaction'?'tree reaction':'tree';if(node.type==='mol'){const img=document.createElement('img');img.src='/api/molecule?smiles='+encodeURIComponent(node.smiles);img.alt='路线中的分子结构';img.loading='lazy';el.append(img,text('code',node.smiles));if(node.closure)el.append(text('span',node.closure==='partial'?'未解决原料':'候选库存 · 未审','tag'));}else el.append(text('span','↓ 预测反应 · 条件与可行性未确认'));for(const child of node.children||[])el.append(treeView(child));return el;}
function render(result){lastResult=result;$('download').hidden=false;$('run-meta').replaceChildren(text('div','实时运行 '+result.run_id),text('div','候选路线 '+result.candidate_count+' · 展示 '+result.routes.length+' · 非实验验证'));
for(const phase of result.phases)$('run-meta').append(text('div',`阶段 ${phase.index+1} · seed ${phase.seed} · ${phase.node_count} 节点 · ${phase.search_seconds.toFixed(2)} s · ${phase.engine_class}`));
$('routes').replaceChildren();if(!result.routes.length)$('routes').append(text('p','本预算没有提取出路线。可调整预算后重新搜索。','empty'));
for(const [index,route] of result.routes.entries()){const card=document.createElement('article');card.className='card route';const heading=document.createElement('div');heading.className='route-head';heading.append(text('h2',`路线 ${index+1}`),text('span',route.closure==='partial'?'部分路线 · 未闭合':'候选闭合 · 无独立证据','tag'));card.append(heading,text('small',route.route_id.slice(0,16)),text('div',`${route.steps} 步 · 未解决原料 ${route.cost.unresolved_materials} · 未指定立体 ${route.cost.unspecified_leaf_stereo} · 暂定成本 ${route.score}`,'cost'));const details=document.createElement('details');details.open=index===0;details.append(text('summary','查看路线结构'),treeView(route.tree));card.append(details);$('routes').append(card);}}
$('search-form').onsubmit=async event=>{event.preventDefault();$('preview').click();$('submit').disabled=true;$('message').textContent='正在执行新的 MCTS 搜索，请保持页面打开…';const req={smiles:$('smiles').value,mode:$('mode').value,seed:Number($('seed').value),candidate_stock:$('candidate').checked};for(const name of ['seconds','iterations'])if($(name).value!=='')req[name]=Number($(name).value);try{const result=await api('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)});render(result);$('message').textContent='本次实时搜索完成。结果仅支持计算探索。';}catch(error){$('message').textContent='搜索失败：'+error.message;}finally{$('submit').disabled=false;}};
$('download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'}));a.download=lastResult.run_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
async function loadRecords(){try{const data=await api(`/api/records?kind=${encodeURIComponent($('kind').value)}&q=${encodeURIComponent($('query').value)}&offset=${offset}`);$('count').textContent=`共 ${data.total} 条 · 当前 ${offset+1}–${Math.min(offset+25,data.total)}`;$('rows').replaceChildren();$('previous').disabled=offset===0;$('next').disabled=offset+25>=data.total;for(const row of data.records){const tr=document.createElement('tr');const raw=row.raw;const label=raw.name||raw.query_name||raw.substance_query||raw.title||raw.fields?.['RXN:VAR(1):CAS_Reaction_Number']||raw.template_id||row.id.slice(0,12);const td=document.createElement('td');const button=text('button','查看','secondary');button.onclick=()=>{$('record-json').textContent=JSON.stringify(row,null,2);$('record-detail').open=true;};td.append(button);tr.append(text('td',label),text('td',row.kind),text('td',row.source_status||row.review_status),td);$('rows').append(tr);}}catch(error){$('count').textContent=error.message;}}
$('find').onclick=()=>{offset=0;loadRecords();};$('kind').onchange=$('find').onclick;$('previous').onclick=()=>{offset=Math.max(0,offset-25);loadRecords();};$('next').onclick=()=>{offset+=25;loadRecords();};
async function loadStatus(){try{const data=await api('/api/status');$('state').textContent=data.state;$('stats').replaceChildren();for(const [name,value] of [['反应记录',data.resources.counts.note_reaction+data.resources.counts.scifinder_reaction],['分子身份',data.resources.counts.molecule],['库存名称冲突',data.resources.name_conflicts],['已晋级生产',data.resources.production_records]]){const el=document.createElement('div');el.className='stat';el.append(text('b',value),text('span',name));$('stats').append(el);}}catch(error){$('state').textContent=error.message;}}
api('/api/targets').then(rows=>{for(const row of rows){const option=text('option',row.name);option.value=row.smiles;$('preset').append(option);}}).catch(error=>{$('message').textContent=error.message;});$('preview').click();
